# Generated by Django 2.0.9 on 2025-10-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereport',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
