# Generated by Django 3.2.25 on 2025-11-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0002_auto_20251028_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
